BEGIN;
ALTER TABLE sites DROP COLUMN IF EXISTS metrics_updated_at;
ALTER TABLE sites DROP COLUMN IF EXISTS instance_label;
ALTER TABLE sites DROP COLUMN IF EXISTS blocked_rate;
ALTER TABLE sites DROP COLUMN IF EXISTS rps;
COMMIT;
