package deploy

import (
	"fmt"
	"strings"
)

type SiteConfig struct {
	Domain    string
	Protocol  string
	Upstreams []string
	SSLName   string
}

type PolicyConfig struct {
	Name       string
	Mode       string
	RuleGroups []RuleGroup
}

type RuleGroup struct {
	Category string
	Rules    []ModsecRule
}

type ModsecRule struct {
	ID       int
	Phase    int
	Severity string
	Message  string
	Match    string
	Operator string
	Pattern  string
	Action   string
}

// GenerateNginxPublic wraps generateNginx for external callers.
func GenerateNginxPublic(site *SiteConfig) string {
	return generateNginx(site)
}

// GenerateModsecPublic wraps generateModsec for external callers.
func GenerateModsecPublic(policy *PolicyConfig) string {
	return generateModsec(policy)
}

func generateNginx(site *SiteConfig) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Generated by waf-control for %s\n", site.Domain))
	b.WriteString("server {\n")
	b.WriteString("    listen 80;\n")
	b.WriteString(fmt.Sprintf("    server_name %s;\n\n", site.Domain))

	if site.Protocol == "https" {
		b.WriteString("    return 301 https://$server_name$request_uri;\n")
		b.WriteString("}\n\n")
		b.WriteString("server {\n")
		b.WriteString("    listen 443 ssl http2;\n")
		b.WriteString(fmt.Sprintf("    server_name %s;\n\n", site.Domain))
		b.WriteString(fmt.Sprintf("    ssl_certificate     /etc/nginx/ssl/%s/fullchain.pem;\n", site.SSLName))
		b.WriteString(fmt.Sprintf("    ssl_certificate_key /etc/nginx/ssl/%s/privkey.pem;\n", site.SSLName))
		b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
		b.WriteString("    ssl_ciphers HIGH:!aNULL:!MD5;\n\n")
	}

	b.WriteString("    modsecurity on;\n")
	b.WriteString(fmt.Sprintf("    modsecurity_rules_file /etc/nginx/modsec/%s.conf;\n\n", site.Domain))

	upstreamName := fmt.Sprintf("backend_%s", strings.ReplaceAll(site.Domain, ".", "_"))
	b.WriteString("    location / {\n")
	b.WriteString(fmt.Sprintf("        proxy_pass http://%s;\n", upstreamName))
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("        proxy_read_timeout 60s;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("upstream %s {\n", upstreamName))
	for _, u := range site.Upstreams {
		b.WriteString(fmt.Sprintf("    server %s;\n", u))
	}
	b.WriteString("}\n")

	return b.String()
}

func generateModsec(policy *PolicyConfig) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Generated by waf-control for policy: %s\n", policy.Name))

	switch policy.Mode {
	case "off":
		b.WriteString("SecRuleEngine Off\n")
	case "detection":
		b.WriteString("SecRuleEngine DetectionOnly\n")
		b.WriteString("SecDefaultAction \"phase:1,log,auditlog,pass\"\n")
	default:
		b.WriteString("SecRuleEngine On\n")
		b.WriteString("SecDefaultAction \"phase:1,log,auditlog,deny,status:403\"\n")
	}

	b.WriteString("\nSecRequestBodyAccess On\n")
	b.WriteString("SecResponseBodyAccess Off\n")
	b.WriteString("SecRequestBodyLimit 13107200\n")
	b.WriteString("SecRequestBodyInMemoryLimit 131072\n\n")

	for _, group := range policy.RuleGroups {
		b.WriteString(fmt.Sprintf("# === %s ===\n", group.Category))
		for _, rule := range group.Rules {
			b.WriteString(formatRule(rule))
		}
		b.WriteString("\n")
	}

	return b.String()
}

func formatRule(r ModsecRule) string {
	action := r.Action
	if r.Severity != "" {
		action = fmt.Sprintf("%s,severity:'%s'", action, r.Severity)
	}
	if r.Message != "" {
		action = fmt.Sprintf("%s,msg:'%s'", action, r.Message)
	}
	action = fmt.Sprintf("%s,id:%d,phase:%d", action, r.ID, r.Phase)
	action = fmt.Sprintf("%s,t:urlDecodeUni,t:lowercase", action)

	return fmt.Sprintf("SecRule %s \"@%s %s\" \"%s\"\n", r.Match, r.Operator, r.Pattern, action)
}
